/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 brain_hologram/scene.gltf --transform 
Files: brain_hologram/scene.gltf [13.35KB] > C:\Users\oishe\OneDrive\Desktop\DevPortfolio\Nextjs-Creative-Portfolio-Starter-Code-Files\3D Models\scene-transformed.glb [946.15KB] (-6987%)
Author: oxterium (https://sketchfab.com/oxterium)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/brain-hologram-09d686a1a1f745cba6b2385d0c831214
Title: Brain hologram
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="Icosphere001" rotation={[-Math.PI / 2, 0, -2.734]} scale={100}>
            <mesh name="Icosphere001_Particle_2_0" geometry={nodes.Icosphere001_Particle_2_0.geometry} material={materials.Particle_2} />
            <mesh name="Icosphere001_Particle_1_0" geometry={nodes.Icosphere001_Particle_1_0.geometry} material={materials.Particle_1} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
